const lang = {
    en:{
        search:"Search",
        gptSearchPlaceholder:"What would you like to watch today?",
        manageProfile:"Manage Profile",
        transferProfile:"Transfer Profile",
        account:"Account",
        helpCenter:"Help Center",
        signOutOfNetflix:"SignOut Of Netflix",
        play:"Play",
        moreInfo:"More info",
        explore:"Explore",
        thisPageProtecte:"This page is protected by Google reCAPTCHA to ensure you're not a bot.",
        learnMore:"Learn More",
        thisInfoIsCollected:"The information collected by Google reCAPTCHA is subject to the Google",
        and:"and",
        andIsUsed:", and is used for providing, maintaining, and improving the reCAPTCHA service and for general security purposes (it is not used for personalised advertising by Google).",
        signIn:"Sign in",
        signUp:"Sign Up",
        signUpNow:"Sign Up now",
        newToNetflix:"New to Netflix? ",
        signInNow:"Sign in Now",
        alreadyAnUser:"Already an User?",
        inCorrectPassword:"Incorrect Password",
        tryAgain:"Please try again or you can",
        resetPassword:"Reset Password",
        accountNotFound:"Sorry, we can't find an account with this email address. Please try again or ",
        inValidEmail:"Please enter a valid email address.",
        inValidPassWord:"Please enter a valid Password.",
        createNewAccount:"Create a New Account .",
        fullNameSpaceHolder:"Full Name",
        emailSpaceHolder:"Email",
        passwordSpaceHolder:"Password",
    },
    hindi:{
        search:"खोज",
        gptSearchPlaceholder:"आज आप क्या देखना चाहेंगे?",
        manageProfile:"प्रोफ़ाइल प्रबंधित करें",
        transferProfile:"प्रोफ़ाइल स्थानांतरण",
        account:"खाता",
        helpCenter:"सहायता केंद्र",
        signOutOfNetflix:"साइन आउट",
        play:"चलाएं",
        moreInfo:"अधिक जानकारी",
        explore:"अन्वेषण",
        thisPageProtecte:"यह पृष्ठ Google reCAPTCHA द्वारा सुरक्षित है ताकि यह सुनिश्चित किया जा सके कि आप बॉट नहीं हैं।",
        learnMore:"अधिक जानें",
        thisInfoIsCollected:"Google reCAPTCHA द्वारा एकत्रित की गई जानकारी Google के अधीन है",
        and:"और",
        andIsUsed:", और इसका उपयोग reCAPTCHA सेवा प्रदान करने, बनाए रखने और सुधारने और सामान्य सुरक्षा उद्देश्यों के लिए किया जाता है (इसका उपयोग Google द्वारा वैयक्तिकृत विज्ञापन के लिए नहीं किया जाता है)।",
        signIn:"साइन in",
        signUp:"साइन अप करें",
        signUpNow:"अभी साइनअप करें",
        newToNetflix:"नेटफ्लिक्स पर नए हैं?",
        signInNow:"अब साइन इन करो",
        alreadyAnUser:"क्या आप पहले से ही एक उपयोगकर्ता हैं?",
        inCorrectPassword:"गलत पासवर्ड",
        tryAgain:"कृपया पुनः प्रयास करें या आप कर सकते हैं",
        resetPassword:"पासवर्ड रीसेट",
        accountNotFound:"क्षमा करें, हमें इस ईमेल पते वाला कोई खाता नहीं मिल सका। कृपया पुनः प्रयास करें या ",
        inValidEmail:"कृपया एक मान्य ईमेल पता प्रविष्ट करें।",
        inValidPassWord:"कृपया एक वैध पासवर्ड दर्ज करें।",
        createNewAccount:"नया खाता बनाएं ।",
        fullNameSpaceHolder:"पूरा नाम",
        emailSpaceHolder:"ईमेल",
        passwordSpaceHolder:"पासवर्ड",
    },
    spanish:{
        search:"buscar",
        gptSearchPlaceholder:"¿Qué te gustaría ver hoy?",
        manageProfile:"gestionar perfil:",
        transferProfile:"Perfil de transferencia",
        account:"cuenta",
        helpCenter:"Centro de ayuda",
        signOutOfNetflix:"Cerrar sesión en Netflix",
        play:"reproducir",
        moreInfo:"más información",
        explore:"explorar",
        thisPageProtecte:"Esta página está protegida por Google reCAPTCHA para garantizar que no seas un bot.",
        learnMore:"Aprende más",
        thisInfoIsCollected:"La información recopilada por Google reCAPTCHA está sujeta a las normas de Google.",
        and:"y",
        andIsUsed:", y se utiliza para proporcionar, mantener y mejorar el servicio reCAPTCHA y con fines de seguridad general (Google no lo utiliza para publicidad personalizada).",
        signIn:"Iniciar sesión",
        signUp:"inscribirse",
        signUpNow:"Regístrate ahora",
        newToNetflix:"¿Nuevo en Netflix?",
        signInNow:"Regístrate",
        alreadyAnUser:"¿Ya eres usuaria?",
        inCorrectPassword:"Contraseña incorrecta",
        tryAgain:"Por favor inténtalo de nuevo o podrás",
        resetPassword:"Restablecer la contraseña",
        accountNotFound:"Lo sentimos, no podemos encontrar una cuenta con esta dirección de correo electrónico. Por favor inténtelo de nuevo o ",
        inValidEmail:"Por favor, introduce una dirección de correo electrónico válida.",
        inValidPassWord:"Por favor introduce una contraseña válida.",
        createNewAccount:"Crea una cuenta nueva .",
        fullNameSpaceHolder:"Nombre completo",
        emailSpaceHolder:"Correo electrónico",
        passwordSpaceHolder:"Contraseña",
    },
    french:{
        search:"recherche",
        gptSearchPlaceholder:"Qu’aimeriez-vous regarder aujourd’hui ?",
        manageProfile:"gérer le profil:",
        transferProfile:"Profil de transfert",
        account:"compte",
        helpCenter:"Centre d'aide",
        signOutOfNetflix:"Se déconnecter de Netflix",
        play:"Lancer le",
        moreInfo:"plus d'informations",
        explore:"explorer",
        thisPageProtecte:"Cette page est protégée par Google reCAPTCHA pour garantir que vous n'êtes pas un robot.",
        learnMore:"Apprendre encore plus",
        thisInfoIsCollected:"Les informations collectées par Google reCAPTCHA sont soumises aux règles de Google",
        and:"et",
        andIsUsed:", et est utilisé pour fournir, maintenir et améliorer le service reCAPTCHA et à des fins de sécurité générale (il n'est pas utilisé pour la publicité personnalisée par Google).",
        signIn:"Se connecter",
        signUp:"s'inscrire",
        signUpNow:"s'inscrire maintenant",
        newToNetflix:"Nouveau sur Netflix ?",
        signInNow:"Connectez vous maintenant",
        alreadyAnUser:"Déjà utilisateur ?",
        inCorrectPassword:"Mot de passe incorrect",
        tryAgain:"Veuillez réessayer ou vous pouvez",
        resetPassword:"Réinitialiser le mot de passe",
        accountNotFound:"Désolé, nous ne trouvons pas de compte avec cette adresse e-mail. Veuillez réessayer ou ",
        inValidEmail:"S'il vous plaît, mettez une adresse email valide.",
        inValidPassWord:"Entrer un mot de passe valide s'il vous plait.",
        createNewAccount:"Créer un nouveau compte .",
        fullNameSpaceHolder:"Nom et prénom",
        emailSpaceHolder:"E-mail",
        passwordSpaceHolder:"Mot de passe",
    },
    punjabi:{
        search:"ਖੋਜ",
        gptSearchPlaceholder:"ਤੁਸੀਂ ਅੱਜ ਕੀ ਦੇਖਣਾ ਚਾਹੋਗੇ?",
        manageProfile:"ਪਰੋਫਾਇਲ ਦਾ ਪ੍ਰਬੰਧਨ ਕਰੋ:",
        transferProfile:"ਪ੍ਰੋਫਾਈਲ ਟ੍ਰਾਂਸਫਰ ਕਰੋ",
        account:"ਖਾਤਾ",
        helpCenter:"ਮਦਦ ਕੇਂਦਰ",
        signOutOfNetflix:"Netflix ਤੋਂ ਸਾਈਨ-ਆਊਟ ਕਰੋ",
        play:"ਚਲਾਓ",
        moreInfo:"ਹੋਰ ਜਾਣਕਾਰੀ",
        explore:"ਪੜਚੋਲ ਕਰੋ",
        thisPageProtecte:"ਇਹ ਪੰਨਾ Google reCAPTCHA ਦੁਆਰਾ ਸੁਰੱਖਿਅਤ ਹੈ ਇਹ ਯਕੀਨੀ ਬਣਾਉਣ ਲਈ ਕਿ ਤੁਸੀਂ ਬੋਟ ਨਹੀਂ ਹੋ।",
        learnMore:"ਜਿਆਦਾ ਜਾਣੋ",
        thisInfoIsCollected:"Google reCAPTCHA ਦੁਆਰਾ ਇਕੱਤਰ ਕੀਤੀ ਜਾਣਕਾਰੀ Google ਦੇ ਅਧੀਨ ਹੈ",
        and:"ਅਤੇ",
        andIsUsed:", ਅਤੇ ਇਸਦੀ ਵਰਤੋਂ reCAPTCHA ਸੇਵਾ ਪ੍ਰਦਾਨ ਕਰਨ, ਸਾਂਭ-ਸੰਭਾਲ ਕਰਨ ਅਤੇ ਸੁਧਾਰ ਕਰਨ ਅਤੇ ਆਮ ਸੁਰੱਖਿਆ ਉਦੇਸ਼ਾਂ ਲਈ ਕੀਤੀ ਜਾਂਦੀ ਹੈ (ਇਸਦੀ ਵਰਤੋਂ Google ਦੁਆਰਾ ਵਿਅਕਤੀਗਤ ਵਿਗਿਆਪਨ ਲਈ ਨਹੀਂ ਕੀਤੀ ਜਾਂਦੀ ਹੈ)।",
        signIn:"ਸਾਈਨ - ਇਨ",
        signUp:"ਸਾਇਨ ਅਪ",
        signUpNow:"ਹੁਣੇ ਸਾਈਨ ਅੱਪ ਕਰੋ",
        newToNetflix:"Netflix ਲਈ ਨਵੇਂ?",
        signInNow:"ਹੁਣੇ ਸਾਈਨ ਇਨ ਕਰੋ",
        alreadyAnUser:"ਕੀ ਪਹਿਲਾਂ ਤੋਂ ਹੀ ਇੱਕ ਉਪਭੋਗਤਾ ਹੈ?",
        inCorrectPassword:"ਗਲਤ ਪਾਸਵਰਡ",
        tryAgain:"ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ ਤੁਸੀਂ ਕਰ ਸਕਦੇ ਹੋ",
        resetPassword:"ਪਾਸਵਰਡ ਰੀਸੈਟ ਕਰੋ",
        accountNotFound:"ਮਾਫ਼ ਕਰਨਾ, ਅਸੀਂ ਇਸ ਈਮੇਲ ਪਤੇ ਨਾਲ ਕੋਈ ਖਾਤਾ ਨਹੀਂ ਲੱਭ ਸਕਦੇ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ ਜਾਂ",
        inValidEmail:"ਇੱਕ ਜਾਇਜ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ.",
        inValidPassWord:"ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਪਾਸਵਰਡ ਦਾਖਲ ਕਰੋ।",
        createNewAccount:"ਨਵਾਂ ਖਾਤਾ ਬਣਾਉ .",
        fullNameSpaceHolder:"ਪੂਰਾ ਨਾਂਮ",
        emailSpaceHolder:"ਈ - ਮੇਲ",
        passwordSpaceHolder:"ਪਾਸਵਰਡ",
    },
    japanese:{
        search:"検索",
        gptSearchPlaceholder:"今日は何を見たいですか？",
        manageProfile:"プロファイルの管理:",
        transferProfile:"プロファイルの転送",
        account:"アカウント",
        helpCenter:"ヘルプセンター",
        signOutOfNetflix:"サインアウト",
        play:"を再生",
        moreInfo:"より詳しい情報",
        explore:"探検する",
        thisPageProtecte:"このページは、ボットではないことを保証するために Google reCAPTCHA によって保護されています。",
        learnMore:"もっと詳しく知る",
        thisInfoIsCollected:"Google reCAPTCHA によって収集された情報は、Google の規制の対象となります。",
        and:"そして",
        andIsUsed:", reCAPTCHA サービスの提供、維持、改善と一般的なセキュリティ目的に使用されます (Google によるパーソナライズされた広告には使用されません)。",
        signIn:"サインイン",
        signUp:"サインアップ",
        signUpNow:"今すぐサインアップ",
        newToNetflix:"Netflix を初めてご利用ですか?",
        signInNow:"今すぐサインイン",
        alreadyAnUser:"すでにユーザーですか?",
        inCorrectPassword:"間違ったパスワード",
        tryAgain:"もう一度お試しください。",
        resetPassword:"パスワードを再設定する",
        accountNotFound:"申し訳ありませんが、このメール アドレスのアカウントは見つかりませんでした。もう一度試してください。または ",
        inValidEmail:"有効なメールアドレスを入力してください。",
        inValidPassWord:"有効なパスワードを入力して下さい。",
        createNewAccount:"新しいアカウントを作成します。",
        fullNameSpaceHolder:"フルネーム",
        emailSpaceHolder:"Eメール",
        passwordSpaceHolder:"パスワード",
    }
}

export default lang;